{% set name = "metis" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: metis-5.1.0.tar.gz
  md5: 5465e67079419a69e0116de24fce58fe
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz

build:
  number: 3
  binary_relocation: true

requirements:
  build:
    - cmake
    - toolchain

test:
  commands:
    - graphchk  # [unix]
    - cmpfillin -h  # [unix]
    - mpmetis -h  # [unix]
    - gpmetis -h  # [unix]
    - ndmetis -h  # [unix]
    - gpmetis -h  # [unix]
    - m2gmetis -h  # [unix]
    - test -f $PREFIX/include/metis.h  # [unix]
    - %LIBRARY_BIN%\graphchk.exe  # [win]
    - %LIBRARY_BIN%\cmpfillin.exe -h  # [win]
    - %LIBRARY_BIN%\mpmetis.exe -h  # [win]
    - %LIBRARY_BIN%\gpmetis.exe -h  # [win]
    - %LIBRARY_BIN%\ndmetis.exe -h  # [win]
    - %LIBRARY_BIN%\gpmetis.exe -h  # [win]
    - %LIBRARY_BIN%\m2gmetis.exe -h  # [win]

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
  license: Apache License 2.0
  license_file: LICENSE.txt
  summary: 'METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    METIS is a set of serial programs for partitioning graphs, partitioning 
    finite element meshes, and producing fill reducing orderings for sparse 
    matrices. The algorithms implemented in METIS are based on the multilevel 
    recursive-bisection, multilevel k-way, and multi-constraint partitioning 
    schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/metis/metis/faq

extra:
  recipe-maintainers:
    - basnijholt
