travis:
  secure:
    BINSTAR_TOKEN: JUT/YAJmVOhQKg7yWZMIj61xshL4iF0E8fske6bevr4ZVB6HCVEUVME3kmjBAxRQ68OyW3FvtxcogGs5TD2ralBUgEvJCmBU8BA8T0dWwmgWdWnucga/qDtjcxHllz9At2Xh6m8WLLyi2yA2bKaOTJpOnqCmc95gmUQUB7fTrZe7XycA46hKMLE7hqs2BNSWcFP6SFhrdy2ryKUShS8Bm4CHZ2kgekrpkmSWE9RtkVtNpcFkR21KiJsSUuo4MKNsEWcrUcDpaPWRSpczUi7ax2el09bIOlR4y6NdPkCfWm061UFqxhsQqDv4kzfWdbLu8RLWer9pkp5kyceq1uPNOyrx9JF8cPR0L4LxW9WdISPb8LinAgJcMF+i3q6z26KUw1Pu75t/bcXg7aN3OWOLDF24aE+WOznYCyXJLMJ3J3Nz8uDhj4grkmIuuN2Swoul/X08UOgIZgGeCnXez406x75eTNhJNHX+fKypBTpoi2GBFjozu/1EKL8qgCxXBVsZmNxC5zBErJEJUYbHonW8fja4F54FDG1b8i0SwDUE7cjy8CuWnT/rraI0RtL2W+428x2v3MZVSf04SDZbegUzbC7Qh479KS9ToQu4tp30VAV47CvD/HjrwluXiZrgwr8EQytaI22G72U8CwGy3uQ49kP74f11DhHJGOecQPubViw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
