travis:
  secure:
    BINSTAR_TOKEN: d22TPL4qgURvelMJtoTjGAGbBpRZ1lzzWh0egNUvQ/4LpkdiJNc3W7ED69No1DXkwk9xq+4xAW4t7JcSCYyLKsgSrQnKTUt2O6fiycHiub54VxStCnBIDYK6zax3x+AMEtfBF1xSqUWHkWu7zdN3w2tq6W59E4xZxPJNxVhpBYE3MD8dgdyGjqjjI8del7qp3Jm4q20AC4g3yTpgkUCrVVDUIHpd4MlwEZUF9QmOMBywZdQE+i9oFYA41RTATC0L1tl3M9NtPf6rX/dzHn8d2yZa0I7NbxxDhrbyD9wZnthWe/NKeiRvkAvPrOuCUInqN/qpkCwTk8bg+mtZmwJXt4wnZ9Akc5T8A+yO/u933KJNkMDoOI9GQtZoGLKAWI1l4dZnND/+nx07WvS/1DtBgopOUlMv7w10bWkAB9sjkaamMHX+XpB0JEQbjvJNkgjDEIYeC0PWCFd2JRx/Zkn02ayEkbWASYekOwRRb8ZjfHW2xvSUfoV4hHBG7SsRjgrjZ6f7l/c2zs+3DsMPMY5XARqQdCYQe9u3PsYAtn6mE3wzRTZS+aoU17YQ1SFHDmuUY9P1NWwSih9EXA6imzK/uj+lfnsFVFS+2cSTkUjIBDC7l7zoM+sa8ru6O95AqCx7j7BKjs2ZY2SnT/qb6r4X+71ehMaMiyUDNDkxzXv0WHM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
