travis:
  secure:
    BINSTAR_TOKEN: Hqqqm7fd6a0n/O161KJNS/KyD0Q2p3pbP6mqUCWjmw5wQiKJ5Rpa8jk5YbHh5Z44zsXwIbzCt5siqO4y6WNTC5f14dDo20AmiKdxgQ4UELV3SE017UPocg/2QWBY/i3gGCDiADty8ovYndnJr3IzRC28kUFthXRc1hTWddjCFkW5XGn/edZ0Ifa+MFuen45LMIW8RMOH+kJtKan+oyvfkJfYPhZyUo5pm00Gf2aw5899aWHLsTA05yAAa4WQRqinfld3ID9N3+XyHdVjkjfJdoYN/Yg/2++QS4o7x9J/vMM+24G7ePxJnU8TWPLj21tf1F3ExMpQrvO6+JkrnABDfNqrszlvzIz51HarxQyGKXCsMvKXTFOz/ENHYz5LatEfbtlxFdFJxu7DJEA351xscLwqc1sC8+0BA75HO3Az0uFgqcnRnD096SM7MRntmgow/+oCKkmOztA0mXYHHjRRXgMvMmt9TdUe5C5snCqWp6w1rQTzBV9BcvLoqv9PrRk0MvTxiq2kmV7OmOYu53Q4abhjuRRUyc+Ie0uS2fibhFuKqOPCnpfq5KMS3buxACpXDCXQGu6MddCqqZYKZfvtRaTBdSLJYOLZorX1DD0XuHIxZY6q1yd0KS43JSmCYervQc7hD5qVJrHUFCjvDG/d1cnsSTJPQ6JEDP+fDjA8z9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
